"""preferences table

Revision ID: e98f0df79f06
Revises: 7f10b88746c5
Create Date: 2026-08-23 19:53:47.470580

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "e98f0df79f06"
down_revision: str | None = "7f10b88746c5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "preferences",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("child_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("context", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "category IN ('food', 'sound', 'texture', 'activity', 'place', 'social', 'other')",
            name="ck_preferences_category",
        ),
        sa.CheckConstraint(
            "kind IN ('like', 'dislike', 'sensory_seeking', 'sensory_avoiding')",
            name="ck_preferences_kind",
        ),
        sa.ForeignKeyConstraint(
            ["child_id"],
            ["children.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_preferences_child_id"), "preferences", ["child_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_preferences_child_id"), table_name="preferences")
    op.drop_table("preferences")
    # ### end Alembic commands ###
