"""activities table and links

Revision ID: d45a7a16e9af
Revises: e98f0df79f06
Create Date: 2026-08-24 00:08:18.967542

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "d45a7a16e9af"
down_revision: str | None = "e98f0df79f06"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activities",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("child_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("icon", sa.String(length=60), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("materials", sa.Text(), nullable=True),
        sa.Column("skill_tags", sa.JSON(), nullable=False),
        sa.Column("context_tags", sa.JSON(), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=True),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["child_id"],
            ["children.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_activities_child_id"), "activities", ["child_id"], unique=False)
    # batch mode: SQLite cannot ALTER in a foreign key, so rebuild the tables
    with op.batch_alter_table("routine_steps") as batch:
        batch.add_column(sa.Column("activity_id", sa.String(length=36), nullable=True))
        batch.create_foreign_key(
            "fk_routine_steps_activity_id_activities", "activities", ["activity_id"], ["id"]
        )
    with op.batch_alter_table("schedule_items") as batch:
        batch.add_column(sa.Column("activity_id", sa.String(length=36), nullable=True))
        batch.create_foreign_key(
            "fk_schedule_items_activity_id_activities", "activities", ["activity_id"], ["id"]
        )


def downgrade() -> None:
    with op.batch_alter_table("schedule_items") as batch:
        batch.drop_constraint("fk_schedule_items_activity_id_activities", type_="foreignkey")
        batch.drop_column("activity_id")
    with op.batch_alter_table("routine_steps") as batch:
        batch.drop_constraint("fk_routine_steps_activity_id_activities", type_="foreignkey")
        batch.drop_column("activity_id")
    op.drop_index(op.f("ix_activities_child_id"), table_name="activities")
    op.drop_table("activities")
